$modelname "props_proshop/Airtank.mdl"
$model "Airtank" "Reference.smd"
$cdmaterials "models\props_proshop\"
$sequence idle "Reference.smd"

$texturegroup skinfamilies {
	{ "airtank_blue.bmp" }
	{ "airtank_blue_nofs.bmp" }
	{ "airtank_green.bmp" }
	{ "airtank_green_nofs.bmp" }
	{ "airtank_red.bmp" }
	{ "airtank_red_nofs.bmp" }
	{ "airtank_yellow.bmp" }
	{ "airtank_yellow_nofs..bmp" }
}