"Resource/UI/ChangeSkinPanel.res"
{
	"ChangeSkin"
	{
		"ControlName"	"CChangeSkinPanel"
		"fieldName"	"ChangeSkin"
		"title"		"Select Appearance"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"615"
		"tall"		"343"
		"autoResize"	"1"
		"pinCorner"	"0"
		"visible"	"1"
		"enabled"	"1"
		"tabPosition"	"0"
	}
	"Label1"
	{
		"ControlName"	"Label"
		"fieldName"	"Label1"
		"xpos"		"30"
		"ypos"		"27"
		"wide"		"510"
		"tall"		"55"
		"wrap"		"1"
		"autoResize"	"0"
		"pinCorner"	"0"
		"visible"	"1"
		"enabled"	"1"
		"tabPosition"	"0"
		"labelText"	"Select from the options below what clothes you'd like to wear."
		"textAlignment"	"north"
		"dulltext"	"0"
		"brighttext"	"0"
	}
	"ImagePanel1"
	{
		"ControlName"	"ImagePanel"
		"fieldName"	"ImagePanelLogo"
		"xpos"		"8"
		"ypos"		"60"
		"wide"		"150"
		"tall"		"200"
		"autoResize"	"0"
		"pinCorner"	"0"
		"visible"	"1"
		"enabled"	"1"
		"tabPosition"	"0"
		"image"		"skin1"
		"scaleImage"	"0"
	}
	"ImagePanel2"
	{
		"ControlName"	"ImagePanel"
		"fieldName"	"ImagePanelLogo"
		"xpos"		"158"
		"ypos"		"60"
		"wide"		"150"
		"tall"		"200"
		"autoResize"	"0"
		"pinCorner"	"0"
		"visible"	"1"
		"enabled"	"1"
		"tabPosition"	"0"
		"image"		"skin2"
		"scaleImage"	"0"
	}
	"ImagePanel3"
	{
		"ControlName"	"ImagePanel"
		"fieldName"	"ImagePanelLogo"
		"xpos"		"308"
		"ypos"		"60"
		"wide"		"150"
		"tall"		"200"
		"autoResize"	"0"
		"pinCorner"	"0"
		"visible"	"1"
		"enabled"	"1"
		"tabPosition"	"0"
		"image"		"skin3"
		"scaleImage"	"0"
	}
	"ImagePanel4"
	{
		"ControlName"	"ImagePanel"
		"fieldName"	"ImagePanelLogo"
		"xpos"		"458"
		"ypos"		"60"
		"wide"		"150"
		"tall"		"200"
		"autoResize"	"0"
		"pinCorner"	"0"
		"visible"	"1"
		"enabled"	"1"
		"tabPosition"	"0"
		"image"		"skin4"
		"scaleImage"	"0"
	}
	"Skin1"
	{
		"ControlName"	"Button"
		"fieldName"	"join"
		"xpos"		"31"
		"ypos"		"267"
		"wide"		"105"
		"tall"		"25"
		"labelText"	"This one!"
		"Command"	"skin1"
		"textAlignment"	"west"
		"autoResize"	"0"
		"pinCorner"	"0"
		"visible"	"1"
		"enabled"	"1"
		"tabPosition"	"0"
	}
	"Skin2"
	{
		"ControlName"	"Button"
		"fieldName"	"join"
		"xpos"		"179"
		"ypos"		"267"
		"wide"		"105"
		"tall"		"25"
		"labelText"	"This one!"
		"Command"	"skin2"
		"textAlignment"	"west"
		"autoResize"	"0"
		"pinCorner"	"0"
		"visible"	"1"
		"enabled"	"1"
		"tabPosition"	"0"
	}
	"Skin3"
	{
		"ControlName"	"Button"
		"fieldName"	"join"
		"xpos"		"332"
		"ypos"		"267"
		"wide"		"105"
		"tall"		"25"
		"labelText"	"This one!"
		"Command"	"skin3"
		"textAlignment"	"west"
		"autoResize"	"0"
		"pinCorner"	"0"
		"visible"	"1"
		"enabled"	"1"
		"tabPosition"	"0"
	}
	"Skin4"
	{
		"ControlName"	"Button"
		"fieldName"	"join"
		"xpos"		"482"
		"ypos"		"267"
		"wide"		"105"
		"tall"		"25"
		"labelText"	"This one!"
		"Command"	"skin4"
		"textAlignment"	"west"
		"autoResize"	"0"
		"pinCorner"	"0"
		"visible"	"1"
		"enabled"	"1"
		"tabPosition"	"0"
	}
	"Decline"
	{
		"ControlName"	"Button"
		"fieldName"	"close"
		"xpos"		"504"
		"ypos"		"310"
		"wide"		"105"
		"tall"		"25"
		"labelText"	"Cancel    "
		"Command"	"Close"
		"textAlignment"	"east"
		"autoResize"	"0"
		"pinCorner"	"0"
		"visible"	"1"
		"enabled"	"1"
		"tabPosition"	"0"
	}
}