$modelname "weapons/v_blazer.mdl"

//really can't quite figure this out yet, working on it.
//$cdmaterials textures
//$cdmaterials models\weapons\v_hand models\weapons\


// reference meshes
$body body "reference"


//$bodygroup barrel
//{
//studio "default"
//studio "stealth"
//studio "boomstick"
//}


$mostlyopaque
$origin 0 0 0



$sequence draw "Draw" fps 30 snap activity ACT_VM_DRAW 1 node Ready
